version: '3'
services:
  gateway:
    build: ../gateway
    command: rake
    volumes:
      - ../gateway:/myapp
      - /bundle
    environment:
      DATABASE_URL: postgres://postgres@db
      REDIS_URL: redis://redis:6379
      RACK_ENV: development
      RAILS_ENV: development
    depends_on:
      - db
      - redis
  wls:
    build: ../wls
    command: rake
    volumes:
      - ../wls:/myapp
      - /bundle
    environment:
      DATABASE_URL: postgres://postgres@db
      REDIS_URL: redis://redis:6379
      RACK_ENV: development
      RAILS_ENV: development
    depends_on:
      - db
      - redis
  db:
    image: postgres:alpine
  redis:
    image: redis:alpine
